[package]
name = "flashcow"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.11.8"
askama = "0.14.0"
anyhow = "1.0.98"

[dependencies.axum]
version = "0.8.4"
features = ["macros"]

[dependencies.tokio]
version = "1.45.0"
features = ["full"]
